batch_size: 32
epochs: 50
accum_iter: 2
visualize_features: false
lr: 0.0001
save_images: false
model_type: simdino
model: vit_tiny
input_size: 256
dataset_type: geobench_chesapeake
dataset_split: 100
method_name: vit_t_ms_fmow_50k_50e
best_epoch: false
nb_classes: 7
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/simdino_checkpoints/vit_t_ms_fmow_50k_50e.pth
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
