batch_size: 64
epochs: 50
accum_iter: 1
visualize_features: false
lr: 0.001
save_images: false
model_type: dinov2_segmentation
model: vit_b
input_size: 32
dataset_type: geobench_so2sat
dataset_split: 100
method_name: copernicusfm_vit_b
best_epoch: false
nb_classes: 17
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
