batch_size: 32
epochs: 50
accum_iter: 2
visualize_features: false
lr: 0.0001
save_images: false
model_type: croma
model: vit_large_patch16
input_size: 256
dataset_type: geobench_crop
dataset_split: 100
method_name: croma_b
best_epoch: false
nb_classes: 10
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/CROMA_base.pt
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
