batch_size: 16
epochs: 50
accum_iter: 4
visualize_features: false
lr: 0.0001
save_images: true
model_type: dinov2_segmentation
model: base_0
input_size: 500
dataset_type: geobench_cattle
dataset_split: 100
method_name: panopticon
best_epoch: true
nb_classes: 2
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
