batch_size: 4
epochs: 50
accum_iter: 16
visualize_features: false
lr: 0.0001
save_images: false
model_type: dinov2_segmentation
model: large_0
input_size: 500
dataset_type: geobench_cattle
dataset_split: 100
method_name: dinov2_l_uf
best_epoch: false
nb_classes: 2
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
