batch_size: 64
epochs: 128
accum_iter: 1
visualize_features: false
lr: 0.0001
save_images: false
model_type: dinov2_segmentation
model: base_0
input_size: 256
dataset_type: geobench_cashew
dataset_split: 100
method_name: dinov2_b
best_epoch: false
nb_classes: 7
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
