batch_size: 32
epochs: 50
accum_iter: 2
visualize_features: false
lr: 0.0001
save_images: false
model_type: terrafm
model: vit_b
input_size: 500
dataset_type: geobench_cattle
dataset_split: 100
method_name: terrafm_vit_b
best_epoch: false
nb_classes: 2
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/TerraFM-B.pth
# wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
