batch_size: 64
epochs: 128
accum_iter: 1
visualize_features: false
lr: 0.0001
save_images: false
model_type: terrafm
model: vit_b
input_size: 224
dataset_type: geobench_crop
dataset_split: 100
method_name: terrafm_vit_b
best_epoch: false
nb_classes: 10
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/TerraFM-B.pth
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
