batch_size: 4
epochs: 50
accum_iter: 1
visualize_features: false
lr: 0.001
save_images: false
model_type: simdino
model: swin_b
input_size: 32
dataset_type: geobench_so2sat
dataset_split: 100
method_name: swin_bm_ms_fmow_350k_100e_dinov2lp34cn_rgb_head_dconv_aug
best_epoch: false
nb_classes: 17
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/simdino_checkpoints/swin_bm_ms_fmow_350k_100e_dinov2lp34cn_rgb_head_dconv_aug.pth
# wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
