batch_size: 16
epochs: 50
accum_iter: 4
visualize_features: false
lr: 0.01
save_images: false
model_type: simdino
model: swin_b
input_size: 256
dataset_type: geobench_cashew
dataset_split: 100
method_name: swin_b_ms_fmow_350k_100e_dinov2lp34cn_rgb_head_dconv_aug_finished
best_epoch: false 
nb_classes: 7
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/simdino_checkpoints/swin_b_ms_fmow_350k_100e_dinov2lp34cn_rgb_head_dconv_aug_finished.pth
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
