batch_size: 64
epochs: 50
accum_iter: 1
visualize_features: false
lr: 0.0001
save_images: false
model_type: croma
model: swin_b
input_size: 128
dataset_type: PASTIS
dataset_split: 100
method_name: croma_b_frozen
best_epoch: false
nb_classes: 20
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/CROMA_base.pt
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
