batch_size: 64
epochs: 128
accum_iter: 1
visualize_features: false
save_images: false
model_type: simdino
model: swin_s
input_size: 512
train_path: /home/train_62classes.csv
test_path: /home/val_62classes.csv
dataset_type: sen1floods11
dataset_split: 100
method_name: debug_method
best_epoch: false
nb_classes: 3
output_dir: satmae_experiments/outputs/outputs-segment-debug
log_dir: satmae_experiments/logs/logs-segment-debug
wandb: null
eval: false
dist_eval: true
num_workers: 10
