batch_size: 8
epochs: 128
accum_iter: 8
visualize_features: false
lr: 0.0001
save_images: true
model_type: segmentation
model: vit_large_patch16
input_size: 512
dataset_type: sen1floods11
dataset_split: 100
method_name: scalemae
best_epoch: false
nb_classes: 3
output_dir: satmae_experiments/outputs/
log_dir: satmae_experiments/logs/
finetune: /home/filip/pretrained_weights/scalemae-vitlarge-800.pth
wandb: dl4rs-experiments
eval: false
dist_eval: true
num_workers: 10
